# Generated by Django 3.2.3 on 2023-01-11 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_category_notes_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='category',
            field=models.CharField(max_length=20),
        ),
    ]
