# Generated by Django 4.1.5 on 2023-01-12 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0003_alter_notes_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notes",
            name="category",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="notes.category",
            ),
        ),
    ]
