# Generated by Django 4.1.5 on 2023-01-12 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0004_alter_notes_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notes",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("GEN", "General"),
                    ("PRI", "Privat"),
                    ("PRO", "Professional"),
                    ("OTH", "Other"),
                ],
                default=None,
                max_length=20,
                null=True,
            ),
        ),
    ]
