# Generated by Django 4.1.5 on 2023-01-14 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0005_alter_notes_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notes",
            name="category",
        ),
    ]
