# Generated by Django 4.1.5 on 2023-01-14 13:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0006_remove_notes_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="name",
        ),
        migrations.AddField(
            model_name="category",
            name="created_at",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name="notes",
            name="created_at",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
