# Generated by Django 4.1.5 on 2023-01-14 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0007_remove_category_name_category_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notes",
            name="category",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="category_notes_set",
                to="notes.category",
            ),
        ),
    ]
