# Generated by Django 4.1.5 on 2023-01-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0008_notes_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="notes",
            name="category",
        ),
        migrations.RemoveField(
            model_name="notes",
            name="created_at",
        ),
        migrations.AddField(
            model_name="category",
            name="name",
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="notes",
            name="note",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="notes",
            name="title",
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
